### ISSUE TITLE
tlgu is outdated

### ISSUE THREAD

**Issue by ghost** [cltk/greek_software_tlgu#3]
A new version, 1.8.2, was released on May 18th.

http://tlgu.carmen.gr/
http://tlgu.carmen.gr/tlgu-1.8.2.zip

Do you think you can upgrade this repository?

Thanks.

**Comment by kylepjohnson** [comment]
Hi thank you, looks like someone just made a PR for this #4 

@rpi-jeedom after I update, would you please try the code and let me know here if it works well?

**Comment by kylepjohnson** [comment]
I have updated the TLGU software at https://github.com/cltk/greek_software_tlgu . From only 5 mins of checking, the converting still seems to work fine, with some improvements, for example this diff (v1.6, then v1.8.2):

```                                   
26c26
< λόγῳ τὸ μυθῶδες ὑπακοῦσαι καὶ λαβεῖν ἱστορίας ὄψιν: 
---
> λόγῳ τὸ μυθῶδες ὑπακοῦσαι καὶ λαβεῖν ἱστορίας ὄψιν· 
36c36
< καὶ μετὰ τοῦ δυνατοῦ τὸ ξυνετὸν ἔχοντες: πόλεων δὲ 
---
> καὶ μετὰ τοῦ δυνατοῦ τὸ ξυνετὸν ἔχοντες· πόλεων δὲ 
38,39c38,39
< συνῴκισε τὰς Ἀθήνας: ἁρπαγὴ δὲ γυναικῶν ἑκατέρῳ 
< πρόσεστιν: οὐδέτερος δὲ δυστυχίαν περὶ τὰ οἰκεῖα καὶ 
---
> συνῴκισε τὰς Ἀθήνας· ἁρπαγὴ δὲ γυναικῶν ἑκατέρῳ 
> πρόσεστιν· οὐδέτερος δὲ δυστυχίαν περὶ τὰ οἰκεῖα καὶ 
49c49
< δὲ ταῖς πόλεσιν υἱοὺς ἐγκατασπείρας ἄρχοντας: ὧν εἷς 
---
> δὲ ταῖς πόλεσιν υἱοὺς ἐγκατασπείρας ἄρχοντας· ὧν εἷς 
56c56
< των ἐκείνην λέγουσι Πιτθέως εἶναι (Hes. Erg. 370): 
---
> των ἐκείνην λέγουσι Πιτθέως εἶναι (Hes. Erg. 370)· 
69c69
< ἔχουσαν (Hendess 20): 
---
> ἔχουσαν (Hendess 20)· 
72c72
<   μὴ λύσῃς πρὶν δῆμον Ἀθηνέων εἰσαφικέσθαι: 
---
>   μὴ λύσῃς πρὶν δῆμον Ἀθηνέων εἰσαφικέσθαι· 
```

You can see here a better use of the high dot mark instead of a colon.

Another file, I can see different angle brackets:

```
50c50
< τερον Κειτούκειτος. οὗτος ὁ ἀνὴρ νόμον εἶχεν <ἴδιον> 
---
> τερον Κειτούκειτος. οὗτος ὁ ἀνὴρ νόμον εἶχεν 〈ἴδιον〉 
```

I tried [the other tlgu commands in our docs](http://docs.cltk.org/en/latest/greek.html#converting-tlg-texts-with-tlgu) and they all work with the exception of one when break_lines is True, `TLGU().convert(<source>, <destination>, break_lines=True)`. I'll follow up on this elsewhere.
